# Generated by Django 2.0.7 on 2019-09-08 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFlights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(max_length=10)),
                ('departureDate', models.DateField()),
                ('departureTime', models.DateTimeField()),
                ('duration', models.CharField(max_length=10)),
                ('stops', models.IntegerField()),
                ('arrivalDate', models.DateField()),
                ('arrivalTime', models.DateTimeField()),
                ('price', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
