# Generated by Django 2.0.7 on 2019-09-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userflights',
            name='arrivalTime',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='userflights',
            name='departureTime',
            field=models.DateTimeField(blank=True),
        ),
    ]
