# Generated by Django 2.0.7 on 2019-09-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20190908_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userflights',
            name='arrivalTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userflights',
            name='departureTime',
            field=models.DateTimeField(null=True),
        ),
    ]
