# Generated by Django 2.0.7 on 2019-09-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_auto_20190908_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='userflights',
            name='arrivalPlace',
            field=models.CharField(default='ABZ', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userflights',
            name='departurePlace',
            field=models.CharField(default='ABZ', max_length=20),
            preserve_default=False,
        ),
    ]
