# Generated by Django 2.0.7 on 2019-09-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_testdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userflights',
            name='arrivalDate',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userflights',
            name='arrivalTime',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userflights',
            name='departureDate',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userflights',
            name='departureTime',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userflights',
            name='stops',
            field=models.IntegerField(null=True),
        ),
    ]
