# Generated by Django 2.0.7 on 2019-09-17 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_auto_20190910_2100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestData',
        ),
    ]
