# Generated by Django 2.0.7 on 2019-09-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertrips',
            name='imgUrl',
            field=models.CharField(default='url', max_length=2083),
            preserve_default=False,
        ),
    ]
