# Generated by Django 2.0.7 on 2019-09-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_usertrips_imgurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertrips',
            name='imgUrl',
            field=models.CharField(blank=True, max_length=2083),
        ),
    ]
